### ISSUE TITLE
App fails to start, "weird error 8"

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#77]
I just checked out the app from git following the instructions from README.md, tried starting it using "npm run start" but it won't start. I'm not skilled enough to solve this problem myself, so if it's a stupid user error, ignore it. From the log on the command line:

```
$ npm run start

> guestimate@0.0.1 start /home/alex/Projects/guesstimate-app
> BUILD_DEV=0 NODE_ENV=development API_ENV=production webpack-dev-server


/home/alex/Projects/guesstimate-app/webpack.config.js:5
var elev = `<script> var _elev = window._elev || {};(function() {
           ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/alex/Projects/guesstimate-app/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/alex/Projects/guesstimate-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by OAGr** [comment]
Right now if you just remove the reference to _elev in 
guesstimate-app/webpack.config.js:5 and line 17 it should work.  It's something about the elev tag breaking, but this isn't too useful when its running locally.  Not sure why this works on my current set up, it broke when I re-installed it.  

Spent some time trying to fix it, not much luck yet.

**Comment by lomignet** [comment]
After remove reference to eleve on line 5 and 17, I now get:

```
/home/guillaume/gits/guesstimate-app/webpack.config.js:6
var wistia = `<script charSet="ISO-8859-1" src="//fast.wistia.com/assets/exter
             ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/guillaume/gits/guesstimate-app/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/guillaume/gits/guesstimate-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```
With extra npm-debug.log :

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart guestimate@0.0.1
7 info start guestimate@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info guestimate@0.0.1 Failed to exec start script
10 verbose stack Error: guestimate@0.0.1 start: `BUILD_DEV=0 NODE_ENV=development API_ENV=development webpack-dev-server`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:743:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
11 verbose pkgid guestimate@0.0.1
12 verbose cwd /home/guillaume/gits/guesstimate-app
13 error Linux 3.16.0-38-generic
14 error argv "node" "/usr/bin/npm" "run" "start"
15 error node v0.10.25
16 error npm  v2.11.2
17 error code ELIFECYCLE
18 error guestimate@0.0.1 start: `BUILD_DEV=0 NODE_ENV=development API_ENV=development webpack-dev-server`
18 error Exit status 8
19 error Failed at the guestimate@0.0.1 start script 'BUILD_DEV=0 NODE_ENV=development API_ENV=development webpack-dev-server'.
19 error This is most likely a problem with the guestimate package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     BUILD_DEV=0 NODE_ENV=development API_ENV=development webpack-dev-server
19 error You can get their info via:
19 error     npm owner ls guestimate
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

```

It seems to be a syntax error, not a reference to a tag. Same as yalla, I have no npm knowledge.

Using npm 2.11.2 on debian/mint.

**Comment by OAGr** [comment]
Actually, looking above, I would bet this would have something to do with your version of node and npm.  I'm using node v4.1.2 and npm v3.3.9

**Comment by yalla** [comment]
Without updating node or npm, a git pull just now helped; the server now starts.

**Comment by OAGr** [comment]
Great to hear.  I have a feeling like @lomignet 's issue may still exist for him, but that is a separate issue.
